### ISSUE TITLE
undefined is not an object (evaluating '_react.PropTypes.bool')

### ISSUE THREAD

**Issue by fab-mont** [redbaron76/navbar-native#21]
I've already set up the vector icons, but I got this error when I simply import the component in my JS file.

**Comment by molkabenamor** [comment]
Hello, I would like to know how did you solved the problem. thank you in advance

**Comment by zedtux** [comment]
Same as @molkabenamor here. I'm facing this error on my iOS and Android apps.

Apparently [it is due to a very old version](https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/192) of the `react-native-keyboard-aware-scroll-view` package. Using yarn to install a newer version (`yarn add react-native-keyboard-aware-scroll-view`) solved this issue (but I have another one now from another package).

The other errors are exactly the same story, `react-native-spinkit` and `react-native-vector-icons` are really too old.
